import { readFileSync } from 'node:fs'
for (const l of readFileSync('.env','utf8').split('\n')){const m=l.match(/^([A-Z_]+)="?(.*?)"?$/);if(m)process.env[m[1]]=m[2]}
process.env.DATABASE_URL=process.env.DIRECT_URL
const { PrismaClient } = await import('@prisma/client')
const db=new PrismaClient()
const album=await db.figusAlbum.count()
const completos=await db.figusAlbum.count({where:{completedAt:{not:null}}})
const ev=await db.figusEvent.count()
const golds=await db.figusGold.findMany({select:{goldIdx:true,winnerName:true,deliveredAt:true}})
const prizes=await db.figusPrize.findMany({select:{prizeKey:true,winnerName:true,claimedAt:true,deliveredAt:true}})
const tr=await db.figusTradeRequest.count()
const inv=await db.figusInventory.findMany({select:{key:true,label:true,total:true,delivered:true}})
const stock=await db.figusCardStock.aggregate({_sum:{issued:true},_count:true})
const triv=await db.figusTrivia.count()
const cod=await db.figusCodigo.count()
console.log('FigusAlbum        :', album, '(completos:', completos+')')
console.log('FigusEvent (feed) :', ev)
console.log('FigusTradeRequest :', tr)
console.log('FigusGold (doradas):', JSON.stringify(golds))
console.log('FigusPrize (premios):', JSON.stringify(prizes))
console.log('FigusInventory    :', JSON.stringify(inv))
console.log('FigusCardStock    : filas', stock._count, '| issued total', stock._sum.issued)
console.log('FigusTrivia       :', triv)
console.log('FigusCodigo       :', cod)
await db.$disconnect()
